[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
merkle_distributor = "BDSchMcYS2porfeisQoVNgtbJeqrgCxTU6bwYaaWY9ci"
solana_vesting_program = "vestuxzJ5p2kp4iZYvt4rdK5UEqypwoX2MzMkHn5auY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
gen = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/generateRoot.ts"
dis = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/newDis.ts"
spl = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/spl.ts"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/spl.mint.ts"